mod def_and_instantiating;
mod tuple;
mod area_rectange;
mod struct_methods;
mod multiple_methods_parameter;
mod struct_function;
mod enums;
mod enum_option;
mod match_control_flow;
mod enum_method;
mod library;

pub use def_and_instantiating::defining_and_instanting;
pub use tuple::tuple;
pub use area_rectange::area_rectange;
pub use struct_methods::struct_methods;
pub use multiple_methods_parameter::multiple_methods_params;
pub use struct_function::struct_function;
pub use enums::enums;
pub use enum_option::enum_option;
pub use match_control_flow::match_public_flow;
pub use enum_method::enum_method;
pub use library::library;
