mod def_and_instantiating;
mod tuple;
mod area_rectange;
mod struct_methods;
mod multiple_methods_parameter;
mod struct_function;
mod enums;
pub use def_and_instantiating::defining_and_instanting;
pub use tuple::tuple;
pub use area_rectange::area_rectange;
pub use struct_methods::struct_methods;
pub use multiple_methods_parameter::multiple_methods_params;
pub use struct_function::struct_function;
pub use enums::enums;